on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore lab1/src/src.fsproj
      - name: Build project
        run: dotnet build ./lab1/src
      - name: Set DOTNET_ROLL_FORWARD
        run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV
      - name: Lint
        run: |
          dotnet tool install -g dotnet-fsharplint
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          dotnet fsharplint lint ./lab1/src
      - name: Formatter
        run: |
          dotnet tool install -g fantomas-tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          fantomas ./lab1/src/*.fs 
      - name: Run project
        run: dotnet run --project ./src
      - name: Tests
        run: |
            dotnet restore lab1/test/test.fsproj
            dotnet build ./lab1/test
            dotnet test ./lab1/test
